version: '2'

services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    depends_on:
      - nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}sonarr/:/config
      - ${MEDIA_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:preview
    container_name: radarr
    depends_on:
      - nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}radarr/:/config
      - ${MEDIA_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
      - nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}lidarr/:/config
      - ${MEDIA_PATH}:/music
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    depends_on:
      - nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}hydra2/:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
    
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    depends_on:
      - nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}ombi/:/config
    ports:
      - 3579:3579
    restart: unless-stopped    

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
    volumes:
      - ${CONFIG_PATH}nzbget/:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
