version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    user: "${USER_ID}:${GROUP_ID}"
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:17.0.0-apache
    user: "${USER_ID}:${GROUP_ID}"
    ports:
      - ${PORT}:80
    depends_on:
      - db
    volumes:
      - ${DATA_PATH}:/var/www/html/data
      - ${CONFIG_PATH}nextcloud/config:/var/www/html/config
      - ${CONFIG_PATH}nextcloud/apps:/var/www/html/apps
    restart: unless-stopped