version: '2'

services:
   nginx:
    image: nginx
    container_name: nginx
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFIG_PATH}nginx/snippets/:/etc/nginx/snuppets:ro
      - ${CONFIG_PATH}certbot/conf:/etc/letsencrypt
      - ${CONFIG_PATH}certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - ${CONFIG_PATH}certbot/conf:/etc/letsencrypt
      - ${CONFIG_PATH}certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped