version: '2'

services:
   nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${CONFIG_PATH}nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFIG_PATH}nginx/snippets/:/etc/nginx/snippets:ro
      - ${CONFIG_PATH}certbot/live/:/etc/letsencrypt/live:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

   certbot:
    image: certbot/dns-google
    container_name: certbot
    volumes:
      - ${CONFIG_PATH}certbot/:/etc/letsencrypt
    restart: unless-stopped
